### ISSUE TITLE
FNA3D support for Retina not working for Vulkan/Metal

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA3D#143]
FNA3D uses the SDL_Vulkan_GetDrawableSize to get the physical retina resolution, however that function has a pre-requisite before it will return the correct information.  The view has to be created first, otherwise the function punts and just returns the logical viewport dimensions.  See explanation in this SDL issue: https://github.com/libsdl-org/SDL/issues/3980

Here is the relevant explanation:

> It just happened to incidentally work on macOS+OpenGL because of a quirk in the implementation of OpenGL window surfaces on macOS. But getting the size of a metal or opengl or vulkan drawable surface doesn't make logical sense until the drawable surface is created. The current behaviour of SDL_GL_GetDrawableSize and SDL_Metal_GetDrawableSize on iOS reflects that fact – ie it doesn't return the size of the GL or Metal drawable before creating one, because there is no GL or Metal drawable to query the size of.
>
> I would actually prefer to have those functions return an error in those situations, but the GetDrawable function signatures don't allow that right now.

It sounds like this should be generally corrected for all FNA3D drivers.

The effects of this issue are an incorrectly sized display on iOS devices and ugly low-resolution graphics. This is specifically affecting iOS, but likely would affect any HighDPI supported Vulkan platform.

**Comment by TheSpydog** [comment]
Unfortunately it's proving more complicated than copy-pasting, for two reasons.
1. The `mtlGet*` functions require a fair amount of infrastructure to hook into the Objective-C runtime. Annoying and verbose, but doable.
2. `SDL_Metal_CreateView` and friends will [error out](https://github.com/libsdl-org/SDL/blob/19ae71b2db3be88b3c363531ac015a56f62781d6/src/video/SDL_video.c#L4690) if SDL_WINDOW_METAL is not set in the window flags. And of course, SDL also fails to initialize the window if you try to pass both METAL and VULKAN as flags.

Apparently it is possible to retrieve the drawable size from MoltenVK via `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` ([source](https://github.com/KhronosGroup/MoltenVK/issues/428#issuecomment-450687675)), but in order to use that we'd need to both have a physical device and access to the function pointer.

I'm thinking we might need to drop down into the native AppKit/UIKit APIs to try to query the window sizes and multiply by contentScale, but I'm really not a fan of that if we could avoid it.

**Comment by flibitijibibo** [comment]
I may just change the rules of the DPI flag then - we need to support multimonitor DPI better anyhow. Will look at this today.
