### ISSUE TITLE
question: possibility for system installed mojoshader?

### ISSUE THREAD

**Issue by Richard-Rogalski** [FNA-XNA/FNA3D#198]
Vulkan-headers has the possibility to be unbundled (building 'just works' if it's installed to the system and not in the srcdir), would it be possible for just the headers and `libmojoshader.so` to be used at buildtime, or does it need to bundle the whole repo too? I just get

```
  Cannot find source file:

    MojoShader/mojoshader.c
```

( if you're curious, I'm packaging FNA and its deps for gentoo, and it's nicer for us to have everything unbundled )

**Comment by flibitijibibo** [comment]
MojoShader usually needs to be statically linked, since it doesn't have a stable ABI - it's probably possible to redo MojoShader's inclusion in our CMakeLists but the subproject's CMake file has a lot more configurations than what FNA3D wants so it might take some work to get it building the same way.

**Comment by Richard-Rogalski** [comment]
Thanks for the response!! :D
That makes sense, I'll probably go ahead with figuring out how to bundle it in the ebuild then.  Thanks for the awesome work!
